import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
app.use(express.json());

const PORT = 3000;

// Lazy initialization of Gemini API
let aiClient: GoogleGenAI | null = null;
function getAI(): GoogleGenAI | null {
  if (!aiClient) {
    const key = process.env.GEMINI_API_KEY;
    if (key && key !== "MY_GEMINI_API_KEY") {
      try {
        aiClient = new GoogleGenAI({ apiKey: key });
      } catch (err) {
        console.error("Failed to initialize GoogleGenAI SDK:", err);
      }
    }
  }
  return aiClient;
}

// 1. AI Homework Solver Endpoint
app.post("/api/gemini/solve", async (req, res) => {
  const { problem, mode, fileAttached } = req.body;
  if (!problem) {
    return res.status(400).json({ error: "Missing problem input" });
  }

  const ai = getAI();
  if (ai) {
    try {
      let prompt = `You are a futuristic, friendly AI tutor named NexaSnap AI. Explain the following student homework/study problem step-by-step: "${problem}".
CRITICAL DIRECTIVE FOR FORMATTING: Do NOT use any mathematical signs, LaTeX formatting, or math delimiters. Never use "$" or "$$" signs, "\\frac", "\\mathbf", "\\stackrel", square root icons, or other Greek/math codes.
Instead, write all mathematical expressions, equations, and steps in plain, standard English text using normal keyboard characters (for example, write "2x - 5 + 5 = 9 + 5" or "x = 7" or "F_g = m * g" or "mg * sin(theta)" or "pi * r^2"). 
Ensure the explanation is highly readable in plain English text characters.`;
      
      if (mode === "voice") {
        prompt += " Provide a highly conversational, punchy audio script style explanation with simplified insights.";
      }
      if (fileAttached) {
        prompt += " Maximize explanation for the attached math formula or code layout.";
      }

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
      });

      const explanation = response.text || "I was unable to process that perfectly. Please see the computed steps below.";
      return res.json({
        success: true,
        explanation,
        solvedBy: "Gemini 3.5 Flash",
        interactiveQuiz: [
          { q: "What is the critical next step after understanding this concept?", options: ["Apply the ratio test", "Double check the bounds", "Perform integration", "State assumptions"], a: 1 }
        ]
      });
    } catch (e: any) {
      console.warn("Gemini solve error, falling back to rich simulation:", e.message);
    }
  }

  // Realistic fallback simulation
  const result = simulateHomeworkSolve(problem, mode);
  return res.json({
    success: true,
    explanation: result.explanation,
    solvedBy: "NexaSnap Local AI Core (Offline Mode)",
    interactiveQuiz: result.quiz,
  });
});

// 2. AI Notes Generator Endpoint
app.post("/api/gemini/notes", async (req, res) => {
  const { topic, style } = req.body;
  if (!topic) {
    return res.status(400).json({ error: "Please provide a study topic" });
  }

  const ai = getAI();
  if (ai) {
    try {
      const prompt = `Generate a complete premium structured study note for students on: "${topic}". Format it with clear bullet points, key takeaways, and a list of definitions. Use markdown syntax. No prose introductions. Style: ${style || "comprehensive"}`;
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
      });
      return res.json({
        success: true,
        notes: response.text,
        topic,
        style,
        mindmap: generateMockMindmap(topic),
      });
    } catch (e: any) {
      console.warn("Gemini notes error, using simulation:", e.message);
    }
  }

  return res.json({
    success: true,
    notes: `# ${topic} — Ultimate Study Hack Sheet\n\n## 🚀 Core Concept Overview\nUnderstanding the fundamental mechanics of **${topic}** is critical for both board exams and Olympiads.\n\n## 📝 Key Formulae & Definitions\n- **Primary Theorem**: $E = mc^2$ scaled for thermodynamic systems.\n- **Secondary Derivative**: $\\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}$ representing instant rate of study progression.\n\n## 🎯 Mindmap Breakdowns\n1. Foundations of ${topic}\n2. Advanced Applications & Cyber Systems\n3. High-Velocity Practice Loops\n\n*Generated by NexaSnap AI Offline Compiler.*`,
    topic,
    style,
    mindmap: generateMockMindmap(topic),
  });
});

// 3. AI Career Roadmap Endpoint
app.post("/api/gemini/roadmap", async (req, res) => {
  const { career } = req.body;
  if (!career) {
    return res.status(400).json({ error: "Missing career path" });
  }

  const isGradeLevel = /\b(9|10|11|12)\b/i.test(career) || /grade/i.test(career);
  const salaryInstruction = isGradeLevel 
    ? `Do NOT include any estimated salary. Set "salary" to ""` 
    : `Include estimated USD annual salary under "salary".`;

  const ai = getAI();
  if (ai) {
    try {
      const prompt = `You are an elite career guidance mentor. ${salaryInstruction}.
      Generate a JSON schema with college suggestions/school plans, salary info, and a 4-step learning roadmap for the topic/class/career: "${career}".
      Format JSON as follows:
      {
        "career": "${career}",
        "salary": "${isGradeLevel ? "" : "Estimates in USD"}",
        "collegeSuggestions": ["Suggested Hub 1", "Suggested Hub 2"],
        "roadmap": [
          {"title": "Step 1", "duration": "Weeks/Months", "skills": ["Skill 1", "Skill 2"], "description": "High level instructional guideline"}
        ]
      }`;
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
      });
      const parsedText = response.text || "{}";
      // Sanitize potential markdown syntax wrappers if returned
      const cleanJson = parsedText.replace(/```json/g, "").replace(/```/g, "").trim();
      const data = JSON.parse(cleanJson);
      if (isGradeLevel) {
        data.salary = "";
      }
      return res.json({ success: true, ...data });
    } catch (e: any) {
      console.warn("Gemini roadmap error or parse failure. Simulating:", e.message);
    }
  }

  const simulated = simulateRoadmap(career);
  if (isGradeLevel) {
    simulated.salary = "";
  }
  return res.json({ success: true, ...simulated });
});

// 4. AI Exam Predictor Endpoint
app.post("/api/gemini/predict", async (req, res) => {
  const { subject, level, classSelection } = req.body;
  if (!subject) {
    return res.status(400).json({ error: "Missing subject field" });
  }

  const ai = getAI();
  if (ai) {
    try {
      const prompt = `Generate 3 predictive high-probability exam questions, key concepts to master, and a difficulty index for the academic topic: "${subject}" at grade/level: "${level || "college"}" tailored specifically for class/year grade level: "${classSelection || "Class 12"}" to give a highly accurate and appropriate standard questions. Be extremely rigorous, precise, and professional.`;
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              confidence: { type: Type.STRING },
              difficulty: { type: Type.STRING },
              predictions: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    question: { type: Type.STRING },
                    probability: { type: Type.STRING },
                    solutionHint: { type: Type.STRING }
                  },
                  required: ["question", "probability", "solutionHint"]
                }
              },
              keyConcepts: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    title: { type: Type.STRING },
                    importance: { type: Type.STRING },
                    explanation: { type: Type.STRING },
                    formula: { type: Type.STRING }
                  },
                  required: ["title", "importance", "explanation"]
                }
              }
            },
            required: ["confidence", "difficulty", "predictions", "keyConcepts"]
          }
        }
      });
      
      const parsedData = JSON.parse(response.text || "{}");
      return res.json({
        success: true,
        predictions: parsedData.predictions,
        keyConcepts: parsedData.keyConcepts,
        difficulty: parsedData.difficulty,
        confidence: parsedData.confidence,
        subject
      });
    } catch (e: any) {
      console.warn("Gemini exam predict error. Simulating fallback...", e.message);
    }
  }

  // Consistent Fallback matching the same JSON structure
  return res.json({
    success: true,
    predictions: [
      {
        question: `Evaluate the boundary conditions and triple integral representing mass conservation of ${subject} under asymmetric thermal gradients.`,
        probability: "89% Probability",
        solutionHint: "Apply Gauss' Divergence Theorem to isolate boundary flux terms and establish thermodynamic equilibrium."
      },
      {
        question: `Determine the primary stability bounds and asymptotic decay rate for a third-order dynamic system of ${subject}.`,
        probability: "75% Probability",
        solutionHint: "Design a Lyapunov scalar candidate function and verify that its orbital derivative is strictly negative-definite."
      },
      {
        question: `Describe the optimal recurrence relation and algorithmic structure to compute a distributed ${subject} index matrix in O(log n) complexity.`,
        probability: "93% Probability",
        solutionHint: "Employ a matrix exponentiation strategy combined with divide-and-conquer sub-grid balance structures."
      }
    ],
    keyConcepts: [
      {
        title: `${subject} Equilibrium Dynamics`,
        importance: "Critical Mastery",
        explanation: "The theoretical boundaries and steady-state conditions where system state transitions balance without infinite entropy growth.",
        formula: "∇ · F = S - ∂ρ/∂t"
      },
      {
        title: "Asymptotic Convergence Criteria",
        importance: "High Importance",
        explanation: "How discrete intervals and algorithmic iterations settle into structural attractors under chaotic perturbations.",
        formula: "lim (n→∞) || x_n - x* || = 0"
      },
      {
        title: "Orthogonal Coordinate Decompositions",
        importance: "Medium Priority",
        explanation: "Decoupling complex multi-variable state fields into independent orthogonal components or eigenvectors for faster solution speeds.",
        formula: "A · v = λ · v"
      }
    ],
    difficulty: level === "olympiad" ? `Extreme (Olympiad Level - ${classSelection || "Class 12"})` : level === "board" ? `Medium-Hard (Board Level - ${classSelection || "Class 12"})` : `Hard (Academic - ${classSelection || "Graduate"})`,
    confidence: "94% Match Probability",
    subject
  });
});

// 5. AI Language Tutor Endpoint
app.post("/api/gemini/tutor", async (req, res) => {
  const { message, chatHistory, language, mode, standard } = req.body;
  
  if (!message) {
    return res.status(400).json({ error: "Missing user message" });
  }

  const ai = getAI();
  if (ai) {
    try {
      // Build system prompt based on user specs and requested prompt
      const systemInstruction = `You are NexaLearn AI — an advanced multilingual AI tutor and conversation partner designed for users worldwide.
Your mission is to help users learn, practice, speak, understand, and improve communication skills in ANY world language through natural conversations, pronunciation coaching, grammar correction, translations, and interactive learning.

You support ALL major international languages including but not limited to: English, Hindi, Marathi, Tamil, Telugu, Bengali, Gujarati, Punjabi, Urdu, Arabic, French, Spanish, Portuguese, German, Italian, Russian, Japanese, Korean, Chinese, Thai, Turkish, Indonesian, Malay, Vietnamese, Dutch, Greek, Hebrew, Persian, Polish, Ukrainian, Romanian, Swahili, Filipino, Nepali, Sinhala, Kannada, Malayalam, Assamese, Sanskrit, Latin, etc.

CURRENT STUDENT SPECIFICATIONS:
- Target Standard/Grade Level: ${standard || "University level"} (Tailor vocabulary and explanation complexity to this grade level perfectly, from Standard/Grade 1 to University graduates)
- Practice Language: ${language || "English"}
- Selected Mode: ${mode || "Daily Conversation"}

Core AI Behavior:
- Speak naturally like a real human tutor.
- Be friendly, supportive, intelligent, and motivating.
- Adapt automatically to beginner, intermediate, or advanced users.
- Keep conversations interactive and engaging.
- Encourage users to continue speaking confidently.
- Use simple explanations for beginners.
- Use fluent native-level communication for advanced learners.

Conversation Rules:
- Always respond naturally.
- Never shame or insult users for mistakes.
- Correct mistakes politely and clearly (and formatting-friendly).
- Continue conversations with follow-up questions.
- Encourage users regularly.
- Keep responses concise unless detailed explanation is requested.

Grammar Correction Style Example:
User: "I goed to market."
AI: "Nice try 😊\nCorrect sentence: 'I went to the market.'\n\nWhat did you buy there?"

Pronunciation Coaching style:
- Break difficult words into syllables.
- Explain pronunciation in simple phonetics.
- Encourage repetition practice.
- Provide accent guidance gently.

Special Learning Modes rules:
- Beginner Mode: Speak slower, simple words, provide side translations.
- Advanced Mode: Elite native vocabulary, challenging idiom usage.
- Kids Mode: Extremely short, high energy, gaming vocabulary.
- IELTS Practice: Structure feedback like IELTS examiners with score estimation.
- Interview Practice: Challenge user with tough career-specific questions.
- Daily Conversation: Friendly, engaging, lightweight feedback.

Please reply to the user message: "${message}". Engage in the requested practice language directly.`;

      // Structure contents with simplified list of messages for history
      const contents = [];
      if (chatHistory && Array.isArray(chatHistory)) {
        for (const msg of chatHistory.slice(-6)) {
          contents.push({
            role: msg.role === "assistant" ? "model" as const : "user" as const,
            parts: [{ text: msg.text }]
          });
        }
      }
      contents.push({
        role: "user" as const,
        parts: [{ text: message }]
      });

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: contents,
        config: {
          systemInstruction: systemInstruction,
        }
      });

      return res.json({
        success: true,
        reply: response.text || "I was unable to formulate a response. Let us try again!",
        provider: "Gemini 3.5 Flash"
      });
    } catch (e: any) {
      console.warn("Gemini tutor error. Falling back to offline simulator...", e.message);
    }
  }

  // Consistent offline responsive simulation
  const reply = simulateLanguageTutorResponse(message, language, mode, standard);
  return res.json({
    success: true,
    reply,
    provider: "NexaLearn Local AI Tutor Core (Offline Mode)"
  });
});

function simulateLanguageTutorResponse(message: string, language: string, mode: string, standard: string) {
  const cleanMsg = message.toLowerCase();
  let langLabel = language || "English";
  let stdLabel = standard || "University";

  if (cleanMsg.includes("hello") || cleanMsg.includes("hi") || cleanMsg.includes("namaste")) {
    return `Hello! 😊 Natural greeting detected. As your NexaLearn AI Language Tutor for **${langLabel}** (${stdLabel} standard), I am thrilled to chat. Let's practice! How are you doing today?`;
  }
  
  if (cleanMsg.includes("went") || cleanMsg.includes("goed")) {
    return `Nice try 😊\n\nCorrect sentence pattern:\n**"I went to the market."**\n\n(We always use the past tense 'went' instead of 'goed' in ${langLabel}).\n\nWhat did you buy or look for there?`;
  }

  if (mode && mode.toLowerCase().includes("ielts")) {
    return `[IELTS Academic Mode - Band 8.5 target] \n\nYour sentence of "${message}" was grammatically intact. For IELTS, we can upgrade the lexical resource by substituting common verbs with advanced synonyms. \n\nHow do you structure your answer for describing hobbies? Let's keep going!`;
  }

  return `Splendid! I have parsed your practice input in **${langLabel}** at the **${stdLabel}** level. You are doing fantastic! Can you share a bit more about your study goals with me?`;
}

// 5b. NexaLearn AI Talk Teacher Mode Endpoint
app.post("/api/gemini/talk-teacher", async (req, res) => {
  const { message, chatHistory, subject, mode, standard, language } = req.body;

  if (!message) {
    return res.status(400).json({ error: "Missing user message" });
  }

  const ai = getAI();
  if (ai) {
    try {
      const systemInstruction = `You are NexaLearn Talk Teacher AI — a highly intelligent, friendly, human-like AI teacher that can teach students through real-time conversations and interactive discussions.
Your role is to behave like a real personal teacher who explains topics clearly, answers questions naturally, motivates students, and teaches in an engaging, conversational style.

CURRENT ACADEMIC PARAMETERS:
- Student Grade/Standard Level: ${standard || "University level"} (Adapt explanations from simple Standard 1 vocabulary to deep University analysis based on this setting)
- Subject: ${subject || "General Knowledge"}
- Special Teaching Mode: ${mode || "Revision Mode"}
- Preferred/Target Language: ${language || "English"}

Core Teacher Personality: Friendly, Smart, Patient, Motivating, Supportive, Professional, Interactive, Human-like.

Teaching Style Guidelines:
- Explain concepts simply first using real-life examples and friendly words.
- Then explain deeply if requested or if appropriate for standard levels.
- Encourage students regularly. Never make them feel embarrassed for mistakes. Correct politely and positively.
- Ask interactive questions or mini challenges during lessons.
- Suggest interactive next-step menus frequently. For example, ask if they would like:
  1. Simple explanation
  2. Markdown Diagram/Visual explanation
  3. Quiz practice / Mini Challenge
  4. Real-life examples

Conversation Rules:
- Keep lessons engaging, concise, and highly interactive.
- Continue conversations with friendly follow-up questions.
- Never give robotic or monotonous responses.

Please reply to the user message: "${message}". Communicate naturally in the requested language: "${language || "English"}".`;

      const contents = [];
      if (chatHistory && Array.isArray(chatHistory)) {
        for (const msg of chatHistory.slice(-6)) {
          contents.push({
            role: msg.role === "assistant" ? "model" as const : "user" as const,
            parts: [{ text: msg.text }]
          });
        }
      }
      contents.push({
        role: "user" as const,
        parts: [{ text: message }]
      });

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: contents,
        config: {
          systemInstruction: systemInstruction,
        }
      });

      return res.json({
        success: true,
        reply: response.text || "Let's explore this topic together! Ask your doubt.",
        provider: "Gemini 3.5 Flash"
      });
    } catch (e: any) {
      console.warn("Gemini talk-teacher error. Transitioning to local simulation...", e.message);
    }
  }

  // Consistent offline responsive simulation
  const reply = simulateTalkTeacherResponse(message, subject, mode, standard, language);
  return res.json({
    success: true,
    reply,
    provider: "NexaLearn Core AI Tutor Engine (Offline Mode)"
  });
});

function simulateTalkTeacherResponse(message: string, subject: string, mode: string, standard: string, language: string) {
  const cleanMsg = message.toLowerCase();
  const subLabel = subject || "Science";
  const stdLabel = standard || "University";
  const langLabel = language || "English";

  if (cleanMsg.includes("photosynthesis")) {
    return `No problem 😊\n\n**Photosynthesis** (under *${subLabel}* for *${stdLabel}*) is the beautiful process plants use to make food using sunlight, water, and carbon dioxide.\n\nThink of it like plants cooking their own food inside their green leaves, using sunlight as energy!\n\nWould you like:\n1. **Simple explanation**\n2. **Diagram explanation**\n3. **Quiz practice trivia**\n4. **Real-life everyday examples**?`;
  }

  if (cleanMsg.includes("hello") || cleanMsg.includes("hi") || cleanMsg.includes("hey") || cleanMsg.includes("teacher")) {
    return `Hello there! 👋 I am your NexaLearn AI Talk Teacher! 🎓\n\nI am thrilled to teach you **${subLabel}** at the **${stdLabel}** level. We are set to **${mode || "Revision Mode"}** practicing in **${langLabel}**.\n\nWhat topic or doubt are we tackling first? You can also ask me for a quick quiz!`;
  }

  if (cleanMsg.includes("quiz") || cleanMsg.includes("test") || cleanMsg.includes("challenge")) {
    return `Excellent decision! Let's do a mini challenge for **${subLabel}** (${stdLabel} level).\n\n**Here is your question:**\nWhat is the primary power house of a biological cell where chemical energy (ATP) is generated?\n\nTake your time! Give me your answer or ask for a Hint! 💡`;
  }

  return `Splendid concept! I have reviewed your point regarding "${message}" under the subject of **${subLabel}**.\n\nSince we are practicing at the **${stdLabel}** level, let's explore this step-by-step. Would you like me to quiz you on this, show a simplified Markdown box diagram, or share a real-world example?`;
}

// Helper Simulation Databases
function simulateHomeworkSolve(problem: string, mode: string) {
  const probLower = problem.toLowerCase();
  let explanation = `🤖 **NexaSnap Solver Engine active.**\n\n### Analytical Breakdown for: "${problem}"\n\n`;

  if (probLower.includes("algebra") || probLower.includes("equation") || probLower.includes("x")) {
    explanation += `1. **Isolate variables**: Group all variable components to the left bounds while stabilizing integer coefficients on the right.\n2. **Factor constants**: Extract prime factors to reduce multi-state variance.\n3. **Resolve quadratic components**: Check convergence against standard formula discriminant (b^2 - 4 * a * c).\n\n💡 **NexaSnap Strategy Tip**: Keeping fractions in simple decimal formats (like 0.5 instead of 1/2) saves time during high-speed board exam competitions!`;
  } else if (probLower.includes("force") || probLower.includes("physics") || probLower.includes("motion") || probLower.includes("velocity")) {
    explanation += `1. **Identify Coordinate Reference Frame**: Draft an immediate free-body diagram highlighting gravity (F_g = m * g) and responsive normal drag vectors.\n2. **Apply Newton's Second Law**: Sum of Forces = m * a along the principal velocity track.\n3. **Decompose multi-axis weights**: Map tangential force components to sine functions for incline angles, e.g. m * g * sin(theta).\n\n⚡ **Cyber Tip**: Use kinetic friction coefficients instead of static friction when acceleration state remains non-zero.`;
  } else if (probLower.includes("chemistry") || probLower.includes("acid") || probLower.includes("reaction")) {
    explanation += `1. **Calculate stoichiometry balances**: Map output moles to inputs using conservation laws.\n2. **Evaluate Lewis structures**: Track free electron valence transfers in the outer shells.\n3. **Compute reaction kinetics**: Apply Arrhenius rate transformations under variable thermodynamic pressure.\n\n🧪 **Lab Note**: Catalysts alter activation energy boundaries without displacing static chemical equilibria.`;
  } else {
    explanation += `1. **Structural Segmentation**: Divide the topic into logical subdivisions (foundation, process, outcome).\n2. **Formula Matching**: Align coefficients with universal principles of the given academic genre.\n3. **Iterative Convergence**: Progress from initial boundary approximations to standard final solutions.\n\n💫 **Quantum Tutor Quote**: "Every complex formula is simply a composition of beautiful, simple ratios. Keep practicing!"`;
  }

  return {
    explanation,
    quiz: [
      { q: `What is the correct fundamental step in solving: "${problem.substring(0,25)}..."?`, options: ["Ignore boundary factors", "Isolate variables and constants", "Convert directly to binary", "Check other answers first"], a: 1 }
    ]
  };
}

function generateMockMindmap(topic: string) {
  return {
    name: topic,
    children: [
      { name: "Foundations", children: [{ name: "Prerequisites" }, { name: "Definitions" }] },
      { name: "Core Algorithms", children: [{ name: "Main Theorems" }, { name: "Common Anomalies" }] },
      { name: "Olympiad Level Hacks", children: [{ name: "Symmetric Simplification" }, { name: "Speed Estimation" }] }
    ]
  };
}

function simulateRoadmap(career: string) {
  return {
    career,
    salary: "$145,000 - $225,000 / Year (Holographic Tech Scale)",
    collegeSuggestions: ["Nexa Institute of Tech", "Neo Stanford Cyber-Lab", "Tokyo Digital Academy"],
    roadmap: [
      { title: "Quantum Basics & Core Prep", duration: "Months 1-3", skills: ["Fundamentals", "Linear Algebra", "Cyber Systems"], description: "Establish standard computational frameworks and build foundational pipelines." },
      { title: "Advanced Architecture Construction", duration: "Months 4-6", skills: ["Machine Learning", "Neural Sync", "Data Flows"], description: "Begin training localized AI engines, optimizing distributed storage models." },
      { title: "Ecosystem Deployment & Security", duration: "Months 7-9", skills: ["Smart Contracts", "Holographic UX", "Crypto-Proofing"], description: "Launch secure real-time protocols and connect deep analytics dashboards." },
      { title: "Grand Master Integration", duration: "Months 10-12", skills: ["Predictive Orchestration", "Global Scaling", "Leaderboard Command"], description: "Deploy full enterprise-ready pipelines with real-time feedback and dynamic rank balancing." }
    ]
  };
}

// Vite integration
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    // Mount Vite middleware in development
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    // Build static assets in production
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`NexaSnap AI Infinity Server running at http://0.0.0.0:${PORT}`);
  });
}

startServer();
